language: python

sudo: false


env:
  - TOX_ENV=py27-django111
  - TOX_ENV=py36-django111
  - TOX_ENV=py36-django20
  - TOX_ENV=py36-django21
  - TOX_ENV=py36-django22


install:
  - pip install tox

script:
- tox -e $TOX_ENV
